# See https://github.com/helm/chart-testing#configuration
remote: 'origin'
target-branch: 'master'
chart-dirs:
  - 'charts'
chart-repos:
  - 'stable=https://charts.helm.sh/stable'
  # - shakahl=https://shakahl.github.io/helm-charts
helm-extra-args: '--timeout 600s'
excluded-charts: []
check-version-increment: false
