apiVersion: v2
name: hasura-graphql-engine

description: Hasura is an instant GraphQL with built-in authorization for your data.

keywords:
  - hasura
  - graphql
  - engine
  - api
  - gateway
  - microservice
  - distributed

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "v1.0.0"

home: https://github.com/hasura/graphql-engine

sources:
  - https://github.com/shakahl/helm-charts/charts/hasura-graphql-engine/

maintainers:
  - name: shakahl
    email: szelpalsoma@gmail.com

engine: gotpl
