{{- if and (.Values.service.enabled) (eq .Values.application.track "stable") -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hasura-graphql-engine.fullname" . }}
  annotations:
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
{{- if .Values.prometheus.metrics }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.internalPort }}"
{{- end }}
  labels:
    {{- include "hasura-graphql-engine.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: {{ .Values.service.protocol | default "TCP" }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "hasura-graphql-engine.selectorLabels" . | nindent 4 }}
{{- end -}}
